# Generated by Django 2.2.10 on 2020-06-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=7)),
                ('date_purchase', models.DateField()),
                ('nib_size', models.CharField(choices=[('B', 'Broad'), ('M', 'Medium'), ('F', 'Fine'), ('EF', 'Extra Fine')], max_length=2)),
            ],
        ),
    ]
